openapi: 3.1.0
info:
  title: devices
  version: '1.8'
servers:
  - url: 'https://integrate.versature.com'
paths:
  /api/devices/users/current:
    get:
      tags:
      - DeviceGroup
      summary: 'Get a list of devices for the authenticated user user. Rate Limit:
        2/second, 5/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/devices/users:
    get:
      tags:
      - DeviceGroup
      summary: 'Get a list of user devices in a domain. Rate Limit: 2/second, 5/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/devices/users/{user}:
    get:
      tags:
      - DeviceGroup
      summary: 'Get a list of devices for a specific user. Rate Limit: 2/second, 5/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user
        in: path
        required: true
        type: string
        description: 'The user/extension to retrieve the devices for. i.e. 101 '
      - $ref: ../models/accept.header.v1.yaml
      - name: Authorization
        in: header
        required: true
        type: string
        description: 'Authorization value. Generally &quot;Bearer ACCESSTOKEN&quot; '
      responses:
        '200':
          description: Success
          schema:
            type: string
components:
  schemas:
    to:
      properties: {}
    
