openapi: 3.1.0
info:
  title: portability
  version: '1.8'
servers:
  - url: 'https://integrate.versature.com'
paths:
  /api/phone_numbers/{phone_number}/portability:
    get:
      tags:
      - NumberPortabilityGroup
      summary: 'Most phone numbers are portable to Versature but this endpoint can
        be used to verify portability.Rate Limit: 5/second, 30/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: phone_number
        in: path
        required: true
        type: number
        description: 'The phone number to verify. E164 format is ideal but a best
          effort will be made to format         the check the number provided. '
      - name: Accept
        in: header
        required: true
        type: string
        description: 'The media type and version which is acceptable for the response. '
      responses:
        '200':
          description: Success
          schema:
            type: boolean
components:
  schemas:
    to:
      properties: {}
