openapi: 3.1.0
info:
  title: presence
  version: '1.8'
servers:
  - url: 'https://integrate.versature.com'
paths:
  /api/presence:
    get:
      tags:
      - DomainPresenceGroup
      summary: 'Get a list of users with their presence on device.Rate Limit: 1/second,
        6/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
components:
  schemas:
    to:
      properties: {}
    
