openapi: 3.1.0
info:
  title: recordings
  version: '1.8'
servers:
  - url: 'https://integrate.versature.com'
paths:
  /api/recordings/call_ids/{call_id}:
    get:
      tags:
      - RecordingsGroup
      summary: 'Get the recordings for a given call by it&#39;s id.Rate Limit: 1/second,
        15/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: call_id
        in: path
        required: true
        type: string
        description: 'The term call id of the recording to fetch '
      - name: Accept
        in: header
        required: true
        type: string
        description: 'The media type and version which is acceptable for the response. '
      - name: Authorization
        in: header
        required: true
        type: string
        description: 'Authorization value. Generally &quot;Bearer ACCESSTOKEN&quot; '
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/recordings/{call_id}:
    get:
      tags:
      - RecordingsGroup
      summary: 'Get the recordings for a given call by it&#39;s id.Rate Limit: 1/second,
        15/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: call_id
        in: path
        required: true
        type: string
        description: 'The term call id of the recording to fetch '
      - name: Accept
        in: header
        required: true
        type: string
        description: 'The media type and version which is acceptable for the response. '
      - name: Authorization
        in: header
        required: true
        type: string
        description: 'Authorization value. Generally &quot;Bearer ACCESSTOKEN&quot; '
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/recordings/{id}:
    get:
      tags:
      - RecordingsGroup
      summary: 'Get the recordings for a given call by it&#39;s id.Rate Limit: 1/second,
        15/minute '
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
        description: 'The term call id of the recording to fetch '
      - name: Accept
        in: header
        required: true
        type: string
        description: 'The media type and version which is acceptable for the response. '
      - name: Authorization
        in: header
        required: true
        type: string
        description: 'Authorization value. Generally &quot;Bearer ACCESSTOKEN&quot; '
      responses:
        '200':
          description: Success
          schema:
            type: string
components:
  schemas:
    to:
      properties: {}
