openapi: 3.1.0
info:
  title: Recordings
  version: '1.8'
  description: Get the recordings for a CDR
servers:
  - url: 'https://integrate.versature.com'
paths:
  '/api/recordings/call_ids/{call_id}':
    get:
      tags:
        - RecordingsGroup
      summary: Get recording
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: call_id
          in: path
          required: true
          type: string
          description: 'The term call id of the recording to fetch '
        - $ref: ../models/accept.header.v1.yaml
        - name: Authorization
          in: header
          required: true
          type: string
          description: 'Authorization value. Generally &quot;Bearer ACCESSTOKEN&quot; '
      responses:
        '200':
          description: Success
          schema:
            type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recording'
              examples:
                example:
                  value:
                    duration: 54
                    url: 'https://record-pri.net2phone.com/LiCf/playback.php?submit=PLAY&asid=sip:example.com&cccid=7250&calid=abcdefghi12345&uid=ui.green.versature.com&time=20161103191117&auth=791fcb5334356b8580952f40d7e60ed7'
                    status: available
      operationId: get-recording
      description: |-
        Get the recordings for a given call by it's id<br>
        **Permission:** Basic User<br>
        **Rate Limit:** 1/second, 15/minute
components:
  schemas:
    to:
      properties: {}
    Recording:
      description: ''
      type: object
      x-examples:
        example:
          duration: 54
          url: 'https://record-pri.net2phone.com/LiCf/playback.php?submit=PLAY&asid=sip:example.com&cccid=7250&calid=abcdefghi12345&uid=ui.green.versature.com&time=20161103191117&auth=791fcb5334356b8580952f40d7e60ed7'
          status: available
      properties:
        duration:
          type: number
          description: The length of the recording in seconds
        url:
          type: string
          minLength: 1
          description: The path to the recorded file
        status:
          type: string
          minLength: 1
          enum:
            - available
            - processing
            - no recording
          description: The status of the recording. 'Available' when it is ready to go. 'Processing' when still being processed and 'No Recording' when it has been deleted or is not available
      required:
        - duration
        - url
        - status
