openapi: 3.1.0
info:
  title: voicemails
  version: '1.8'
servers:
  - url: 'https://integrate.versature.com'
tags:
  - APIs
paths:
  '/api/voicemails/users/{user}/count':
    get:
      tags:
        - APIs
      summary: User voicemail count
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: path
          required: true
          type: string
          description: 'The user you want voicemail count for '
        - $ref: ../models/accept.header.v1.yaml
        - name: Authorization
          in: header
          required: true
          type: string
          description: 'Authorization value. Generally &quot;Bearer ACCESSTOKEN&quot; '
      responses:
        '200':
          description: Success
          schema:
            type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoicemailCount'
              examples:
                example:
                  value:
                    new: 1
                    saved: 2
      operationId: get-voicemail-count
      description: |-
        Get the voicemail count for a user in a domain.<br>
        **Permission** Basic User<br>
        **Rate Limit:** 1/second, 5/minute
components:
  schemas:
    VoicemailCount:
      description: ''
      type: object
      x-examples:
        example:
          new: 1
          saved: 2
      properties:
        new:
          type: number
          minimum: 0
          example: 1
          description: The total count of new voicemails for the specified user
        saved:
          type: number
          minimum: 0
          example: 2
          description: The total count of saved voicemails for the specified user
      required:
        - new
        - saved
