openapi: 3.1.0
info:
  title: voicemails
  version: '1.8'
servers:
  - url: 'https://integrate.versature.com'
paths:
  '/api/voicemails/users/{user}/count':
    get:
      tags:
        - VoicemailsGroup
      summary: 'Get the voicemail count for a user in a domain.Rate Limit: 1/second, 5/minute '
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: path
          required: true
          type: string
          description: 'The user you want voicemail count for '
        - $ref: ../models/accept.header.v1.yaml
        - name: Authorization
          in: header
          required: true
          type: string
          description: 'Authorization value. Generally &quot;Bearer ACCESSTOKEN&quot; '
      responses:
        '200':
          description: Success
          schema:
            type: string
components:
  schemas:
    to:
      properties: {}
